CREATE TABLE libros ( 
   id BIGINT NOT NULL AUTO_INCREMENT ,
   titulo VARCHAR(40) NOT NULL , 
   precio DOUBLE NOT NULL , 
   fecha DATE NULL , 
   PRIMARY KEY (id)) ENGINE = InnoDB;

INSERT INTO libros VALUES (1, 'PHP', 20, '2010/12/01');
INSERT INTO libros VALUES (2, 'Java', 22, '2012/11/02');
INSERT INTO libros VALUES (3, 'Phyton', 25, '2013/01/13');